project:
  type: website

website:
  title: "Outcomes of Infectious Diseases from 2001-2014"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - href: fitted_model_explanation.qmd
        text: Bayesian Model
      - href: HIV.qmd
        text: HIV 
      - href: Malaria.qmd
        text: Malaria
      - href: E.coli.qmd
        text: E. Coli 
      - href: about.qmd
        text: About Me
      - href: Source.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



